import React from 'react';
import { Shield, Sparkles, Database } from 'lucide-react';

export const Footer: React.FC = () => {
  return (
    <footer className="bg-slate-900 text-slate-400 border-t border-slate-800 py-4 px-4 sm:px-6 lg:px-8 text-xs">
      <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <Shield className="w-4 h-4 text-blue-400 flex-shrink-0" />
          <span className="font-semibold text-slate-200">SwasthyaFlow AI</span>
          <span className="text-slate-500">—</span>
          <span className="text-slate-400">National Health Resource Intelligence Platform (Hackathon Prototype)</span>
        </div>

        <div className="flex flex-wrap items-center justify-center gap-4 text-slate-400 text-[11px]">
          <span className="flex items-center gap-1">
            <Database className="w-3.5 h-3.5 text-slate-400" />
            Simulated / Demo Healthcare Dataset
          </span>
          <span className="flex items-center gap-1 text-indigo-300 font-medium">
            <Sparkles className="w-3.5 h-3.5 text-indigo-400" />
            AI Insights Generated by Google Gemini
          </span>
        </div>
      </div>
    </footer>
  );
};
