import React from 'react';
import { Sparkles, Info } from 'lucide-react';

interface AiBadgeProps {
  source?: string;
  className?: string;
  showDisclaimer?: boolean;
}

export const AiBadge: React.FC<AiBadgeProps> = ({
  source = 'Google Gemini 3.8 Flash',
  className = '',
  showDisclaimer = false,
}) => {
  return (
    <div className={`space-y-1 ${className}`}>
      <div className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold bg-indigo-50 text-indigo-700 border border-indigo-200 shadow-xs">
        <Sparkles className="w-3.5 h-3.5 text-indigo-600 animate-pulse" />
        <span>Generated by {source}</span>
      </div>

      {showDisclaimer && (
        <div className="flex items-center gap-1 text-[11px] text-slate-500 italic">
          <Info className="w-3 h-3 text-slate-400" />
          <span>AI analysis is based on simulated prototype data for hackathon evaluation.</span>
        </div>
      )}
    </div>
  );
};
